/**
 * Shared known-answer vectors (spec/vectors-plan.md §1), generated by ndsr (`tests/platform_vectors.rs`) and
 * checked in here as `spec/vectors/platform-vectors.json`. When the platform workspace is present the checked-in
 * copy must equal `../spec/vectors/platform-vectors.json` (re-copy it when the spec changes).
 *
 * Groups the store computes and checks here:
 *   project_id       projectId() incl. slug rejections (develop wizard, prepare cross-check)
 *   subscription_id  subscriptionId() (subscribe flow)
 *   consensus        consensusHash() (manifest digest, Register payload check — errata E11)
 *   keys.node_seeds  nodeIdFromPublicKey() (device pages, binding checks)
 *   binding          bindingMessage() / checkBindingMessage() / checkBindingRecord() + owner EIP-191 signature
 *                    (binding sign requests from the miner, PLATFORM.md §c.2)
 * Groups the store does not compute (Hub, validators and miners own them): amounts, audit, beacon,
 * committee_tally, evidence, finality, merkle, network_params, receipt_v2, snapshot, sortition, task_round,
 * task_vote, units, weights.
 */
import { describe, expect, it } from 'vitest';
import { existsSync, readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { verifyMessage } from 'viem';
import { nodeIdFromPublicKey, projectId, subscriptionId } from './ids';
import { consensusHash } from './manifest';
import { BindingError, bindingMessage, checkBindingMessage, checkBindingRecord, parseBindingMessage } from './binding';
import type { Manifest } from '$lib/api/types';

type BindingRecord = Parameters<typeof checkBindingRecord>[0] & { owner_signature?: string | null };
type Case = { name: string; input: Record<string, unknown>; output?: Record<string, unknown>; error?: string };
type Vectors = Record<string, unknown> & {
	project_id: Case[];
	subscription_id: Case[];
	binding: Case[];
	consensus: { value: Manifest['consensus']; consensus_hash: string };
	keys: { node_seeds: { name: string; node_id: string; public_key: string }[] };
};

const FIXTURE = resolve(process.cwd(), 'spec/vectors/platform-vectors.json');
const WORKSPACE = resolve(process.cwd(), '../spec/vectors/platform-vectors.json');
const raw = readFileSync(FIXTURE, 'utf8');
const v = JSON.parse(raw) as Vectors;

const STORE_GROUPS = ['project_id', 'subscription_id', 'consensus', 'keys', 'binding'];
const NOT_STORE = ['amounts', 'audit', 'beacon', 'committee_tally', 'evidence', 'finality', 'merkle', 'network_params', 'receipt_v2', 'snapshot', 'sortition', 'task_round', 'task_vote', 'units', 'weights'];

function code(fn: () => unknown): string | null {
	try {
		fn();
		return null;
	} catch (e) {
		return (e as { code?: string }).code ?? 'error';
	}
}

describe('platform known-answer vectors', () => {
	it('fixture is the current spec copy and every group is accounted for', () => {
		if (existsSync(WORKSPACE)) expect(raw, 're-copy ../spec/vectors/platform-vectors.json').toBe(readFileSync(WORKSPACE, 'utf8'));
		const groups = Object.keys(v).filter((k) => !k.startsWith('_'));
		expect(groups.sort()).toEqual([...STORE_GROUPS, ...NOT_STORE].sort());
	});

	it('project_id', () => {
		expect(v.project_id.length).toBeGreaterThan(0);
		for (const c of v.project_id) {
			const fn = () => projectId(String(c.input.developer), String(c.input.slug));
			if (c.error) expect(code(fn), c.name).toBe(c.error);
			else expect(fn(), c.name).toBe(c.output!.project_id);
		}
	});

	it('subscription_id', () => {
		expect(v.subscription_id.length).toBeGreaterThan(0);
		for (const c of v.subscription_id) {
			expect(subscriptionId(String(c.input.project_id), String(c.input.owner), String(c.input.node_key)), c.name).toBe(c.output!.subscription_id);
		}
	});

	it('consensus_hash', () => {
		expect(consensusHash(v.consensus.value)).toBe(v.consensus.consensus_hash);
	});

	it('node ids from node keys', () => {
		expect(v.keys.node_seeds.length).toBeGreaterThan(0);
		for (const k of v.keys.node_seeds) expect(nodeIdFromPublicKey(k.public_key), k.name).toBe(k.node_id);
	});

	it('binding: messages, records and owner signatures', async () => {
		const positives = v.binding.filter((c) => !c.error);
		const negatives = v.binding.filter((c) => c.error);
		expect(positives.length).toBeGreaterThan(0);
		expect(negatives.length).toBeGreaterThan(0);
		for (const c of positives) {
			const r = c.output!.record as BindingRecord;
			const exp = { network: String(c.input.network), chainId: Number(c.input.chain_id), owner: r.owner, now: Number(c.input.issued_at) };
			const f = parseBindingMessage(r.message);
			expect(bindingMessage(f), c.name).toBe(r.message);
			if (c.output!.message) expect(r.message, c.name).toBe(c.output!.message);
			expect(f.unbind, c.name).toBe(c.name.startsWith('unbind'));
			checkBindingRecord(r, exp);
			if (r.owner_signature) {
				expect(await verifyMessage({ address: r.owner as `0x${string}`, message: r.message, signature: r.owner_signature as `0x${string}` }), c.name).toBe(true);
			}
		}
		for (const c of negatives) {
			const fn = () => {
				if (typeof c.input.message === 'string') return parseBindingMessage(c.input.message);
				const r = c.input.record as Parameters<typeof checkBindingRecord>[0];
				return checkBindingRecord(r, {
					network: 'necter-testnet',
					chainId: Number(c.input.chain_id ?? 11155111),
					now: Number(c.input.now ?? r.issued_at)
				});
			};
			expect(code(fn), c.name).toBe(c.error);
		}
	});

	it('binding checks refuse another owner', () => {
		const r = v.binding[0].output!.record as BindingRecord;
		expect(() => checkBindingMessage(r.message, { network: 'necter-testnet', chainId: 11155111, owner: '0x' + '11'.repeat(20), now: r.issued_at })).toThrow(BindingError);
	});
});
