/**
 * Known-answer vectors (spec/vectors-plan.md §1): the store must pass the groups project_id, manifest,
 * vault_address, subscription_id, siwe (implemented here) plus beacon, snapshot, weights, sortition, merkle,
 * amounts, receipt_v2, eip712 (not used by the UI yet — reported as pending).
 *
 * The official file `spec/vectors/platform-vectors.json` is generated by ndsr (`tests/platform_vectors.rs`).
 * It is looked up in the platform workspace (../spec/vectors) and in this repo (spec/vectors); until it exists the
 * suite is skipped and the independent Python reference checks in protocol.test.ts cover the same functions.
 */
import { describe, expect, it } from 'vitest';
import { existsSync, readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { projectId, subscriptionId, vaultAddress } from './ids';
import { digestManifest, verifySignedManifest } from './manifest';
import { buildSiweMessage } from './siwe';
import type { Manifest } from '$lib/api/types';

type Case = { name: string; input: Record<string, unknown>; output?: unknown; error?: string };
type Vectors = Record<string, Case[]>;

const candidates = [resolve(process.cwd(), '../spec/vectors/platform-vectors.json'), resolve(process.cwd(), 'spec/vectors/platform-vectors.json')];
const file = candidates.find((p) => existsSync(p));
const vectors: Vectors | null = file ? (JSON.parse(readFileSync(file, 'utf8')) as Vectors) : null;

function out(c: Case, key: string): unknown {
	if (c.output && typeof c.output === 'object' && key in (c.output as object)) return (c.output as Record<string, unknown>)[key];
	return c.output;
}

function errored(fn: () => unknown): string | null {
	try {
		fn();
		return null;
	} catch (e) {
		return (e as { code?: string }).code ?? (e instanceof Error ? e.message : String(e));
	}
}

describe.skipIf(!vectors)('platform known-answer vectors', () => {
	const v = vectors ?? {};

	it('project_id', () => {
		for (const c of v.project_id ?? []) {
			const fn = () => projectId(String(c.input.developer), String(c.input.slug));
			if (c.error) expect(errored(fn), c.name).toBe(c.error);
			else expect(fn(), c.name).toBe(out(c, 'project_id'));
		}
	});

	it('subscription_id', () => {
		for (const c of v.subscription_id ?? []) {
			const got = subscriptionId(String(c.input.project_id), String(c.input.owner), String(c.input.node_key));
			expect(got, c.name).toBe(out(c, 'subscription_id'));
		}
	});

	it('vault_address', () => {
		for (const c of v.vault_address ?? []) {
			const got = vaultAddress(String(c.input.factory), String(c.input.implementation), String(c.input.project_id));
			expect(got, c.name).toBe(String(out(c, 'vault') ?? out(c, 'vault_address')).toLowerCase());
		}
	});

	it('manifest', async () => {
		for (const c of v.manifest ?? []) {
			const m = (c.input.manifest ?? c.input) as unknown as Manifest;
			if (c.error) {
				const env = { manifest: m, sig_type: 'eip191' as const, signature: String(c.input.signature ?? '0x' + '00'.repeat(65)) };
				const r = await verifySignedManifest(env).catch(() => ({ ok: false }));
				expect(r.ok, c.name).toBe(false);
				continue;
			}
			const d = digestManifest(m);
			const o = c.output as Record<string, unknown>;
			if (o.canonical) expect(d.canonical, c.name).toBe(o.canonical);
			if (o.manifest_hash) expect(d.manifest_hash, c.name).toBe(o.manifest_hash);
			if (o.consensus_hash) expect(d.consensus_hash, c.name).toBe(o.consensus_hash);
			if (o.signature) {
				const r = await verifySignedManifest({ manifest: m, sig_type: 'eip191', signature: String(o.signature) });
				expect(r.ok, c.name).toBe(true);
			}
		}
	});

	it('siwe (message construction)', () => {
		for (const c of v.siwe ?? []) {
			if (c.error) continue; // negative cases are Hub-side checks
			const i = c.input as Record<string, string | number>;
			const msg = buildSiweMessage({
				domain: String(i.domain),
				address: String(i.address),
				statement: String(i.statement ?? 'Sign in to Necter testnet.'),
				uri: String(i.uri),
				chainId: Number(i.chain_id ?? i.chainId),
				nonce: String(i.nonce),
				issuedAt: Number(i.issued_at),
				expirationTime: i.expiration_time ? Number(i.expiration_time) : null
			});
			expect(msg, c.name).toBe(out(c, 'message'));
		}
	});
});

describe('vectors file', () => {
	it.skipIf(!!vectors)('is not generated yet (spec/vectors/platform-vectors.json) — Python reference checks run instead', () => {
		expect(vectors).toBeNull();
	});
});
