#!/usr/bin/env python3
"""Independent Python reference values for the store's protocol code (PLATFORM.md §a.2, §d.1, contracts §4.2).

Not the official known-answer file (spec/vectors/platform-vectors.json is generated by ndsr); this is a
cross-implementation check using the same primitives the Hub uses (json.dumps canonical form, eth_hash keccak,
eth_account EIP-191). Requires: pip install "eth-hash[pycryptodome]" eth-account eth-abi

    python3 scripts/gen-reference-vectors.py > src/lib/protocol/fixtures/reference-python.json
"""
import json
from eth_hash.auto import keccak
from eth_abi import encode as abi_encode
from eth_account import Account
from eth_account.messages import encode_defunct

DEV_KEY = "0x" + "00" * 31 + "01"
OWNER_KEY = "0x" + "00" * 31 + "02"
DEV = Account.from_key(DEV_KEY).address.lower()
OWNER = Account.from_key(OWNER_KEY).address.lower()


def canonical(o):
    return json.dumps(o, sort_keys=True, separators=(",", ":"), ensure_ascii=False)


def h(b):
    return "0x" + keccak(b).hex()


def project_id(dev, slug):
    return h(b"necter-project-v1:" + bytes.fromhex(dev[2:]) + slug.encode())


def vault(factory, impl, pid):
    init = bytes.fromhex("3d602d80600a3d3981f3363d3d373d3d3d363d73" + impl[2:] + "5af43d82803e903d91602b57fd5bf3")
    raw = keccak(b"\xff" + bytes.fromhex(factory[2:]) + bytes.fromhex(pid[2:]) + keccak(init))
    return "0x" + raw[12:].hex()


def manifest(slug, name, version=1, previous=None, listing_extra=None):
    pid = project_id(DEV, slug)
    m = {
        "v": 1, "network": "necter-testnet", "chain_id": 11155111, "developer": DEV, "slug": slug,
        "version": version, "previous": previous,
        "consensus": {
            "modules": {"worker": "0x" + "ab" * 32, "verifier": None},
            "work": {"class": "deterministic", "verification": "redundant-execution", "execution": "committee",
                     "functions": ["score"], "task_source": {"kind": "api"}, "max_gas_limit": 50000000,
                     "committee": {"size": 5, "backups": 3, "min_size": 3,
                                   "selection": "collateral-reputation-sortition-v1", "weight_cap_multiple": 10},
                     "round_secs": 60, "lease_secs": 30, "epoch_secs": 3600, "dispute_window_secs": 86400},
            "economics": {"reward_token": "0x000000000000000000000000000000000000ec7a",
                          "vault": vault("0x000000000000000000000000000000000000fac7",
                                         "0x0000000000000000000000000000000000001111", pid),
                          "reward_model": "per-unit", "reward_per_unit": "1000000000000000",
                          "daily_emission": "1000000000000000000000",
                          "fee_split_bp": {"miner": 8500, "developer": 1000, "treasury": 500},
                          "max_units_per_epoch": 1000000, "max_recipients_per_epoch": 2000,
                          "min_collateral": "10000000000000000000",
                          "slashing_bp": {"invalid_result": 1000, "missed_sla": 100}}},
        "scheduling": {"requirements": {"device_classes": ["desktop", "laptop", "phone", "server"], "cpu_cores": 2,
                                        "ram_mb": 2048, "storage_mb": 512, "gpu": None, "min_benchmark": 0,
                                        "engines": ["native", "pulley32", "pulley64"], "attestation": []},
                       "sla": {"max_latency_ms": 2000, "min_uptime_bp": 9500}, "public_tasks": False},
        "listing": {"name": name, "tagline": "Verified weather data for dapps", "description": "Line one\nline \"two\" \t tab",
                    "category": "data-sovereignty", "tags": ["oracle", "weather"],
                    "icon": "https://testnet-rpc.necter.network/v1/assets/" + "0" * 64, "banner": None,
                    "screenshots": [], "video": None, "website": "https://example.org", "docs": None, "support": None,
                    "features": ["Runs on phones"], "accent_color": "#FFC933"},
    }
    if listing_extra:
        m["listing"].update(listing_extra)
    return m


def manifest_case(name, m):
    c = canonical(m)
    sig = Account.sign_message(encode_defunct(primitive=c.encode()), DEV_KEY).signature.hex()
    if not sig.startswith("0x"):
        sig = "0x" + sig
    return {
        "name": name, "manifest": m, "canonical": c, "canonical_hex": "0x" + c.encode().hex(),
        "manifest_hash": h(c.encode()), "consensus_hash": h(canonical(m["consensus"]).encode()),
        "project_id": project_id(m["developer"], m["slug"]), "signature": sig, "signer": DEV,
    }


m1 = manifest("weather-oracle", "Weather Oracle")
m2 = manifest("weather-oracle", "Wetter-Orakel — Ünïcödé ✓ 🐝", version=2,
              previous=h(canonical(m1).encode()), listing_extra={"tagline": "Λ données météo"})

siwe_msg = "\n".join([
    "testnet.necter.network wants you to sign in with your Ethereum account:",
    Account.from_key(OWNER_KEY).address,
    "", "Sign in to Necter testnet.", "",
    "URI: https://testnet.necter.network", "Version: 1", "Chain ID: 11155111",
    "Nonce: AbCdEfGhIjKlMnOpQ", "Issued At: 2026-10-07T12:00:00Z", "Expiration Time: 2026-10-08T00:00:00Z",
])
siwe_sig = Account.sign_message(encode_defunct(text=siwe_msg), OWNER_KEY).signature.hex()
if not siwe_sig.startswith("0x"):
    siwe_sig = "0x" + siwe_sig

out = {
    "keys": {"dev": DEV, "owner": OWNER},
    "canonical": [
        {"input": {"b": 1, "a": [True, None, "x"], "é": "ü", "A": {"z": 0, "y": -5}}, "output": canonical({"b": 1, "a": [True, None, "x"], "é": "ü", "A": {"z": 0, "y": -5}})},
        {"input": {"\U0001F41D": 1, "￿": 2, "ctl": "\u0001\u007f "}, "output": canonical({"\U0001F41D": 1, "￿": 2, "ctl": "\u0001\u007f "})},
    ],
    "project_id": [
        {"developer": DEV, "slug": s, "project_id": project_id(DEV, s)}
        for s in ["abc", "weather-oracle", "a" * 48, "0-9"]
    ],
    "subscription_id": [
        {"project_id": project_id(DEV, "weather-oracle"), "owner": o, "node_key": "0x" + "11" * 32,
         "subscription_id": h(abi_encode(["bytes32", "address", "bytes32"],
                                         [bytes.fromhex(project_id(DEV, "weather-oracle")[2:]), o, b"\x11" * 32]))}
        for o in [OWNER, DEV]
    ],
    "vault_address": [
        {"factory": "0x000000000000000000000000000000000000fac7", "implementation": "0x0000000000000000000000000000000000001111",
         "project_id": p, "vault": vault("0x000000000000000000000000000000000000fac7", "0x0000000000000000000000000000000000001111", p)}
        for p in [project_id(DEV, "weather-oracle"), project_id(DEV, "abc")]
    ],
    "manifest": [manifest_case("v1 api source", m1), manifest_case("v2 listing-only non-ascii", m2)],
    "siwe": {"message": siwe_msg, "signature": siwe_sig, "address": OWNER},
}
print(json.dumps(out, indent=2, ensure_ascii=False))
